# server 설정
server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 설정
spring:
  data:
    redis:
      host: localhost
      port: 6379
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

  main:
    allow-bean-definition-overriding: true

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/LUMEN?serverTimezone=UTC&characterEncoding=UTF-8
    username: LUMEN
    password: VIKING
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: com.lumeneditor.www.config.CustomNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy


# JWT 설정
jwt:
  secret: 64461f01e1s23mf93ngrg2fd9501ce59142452199ff112fb5404c8e7e98e3ff


# 로그설정
logging:
  level:
    root: INFO
    com.lumeneditor.www: DEBUG
  file:
    name: logs/myapp.log
