# server 설정
server:
  port: 8001
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Spring 설정
spring:
  main:
    allow-bean-definition-overriding: true

  # MySQL 설정
  datasource:
    url: jdbc:mysql://localhost:3306/LUMEN?serverTimezone=UTC&characterEncoding=UTF-8
    username: LUMEN
    password: VIKING
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      show-sql: true # System.out로 SQL 문을 출력합니다.
      hibernate:
        ddl-auto: create # 애플리케이션 시작 시 데이터베이스 스키마를 생성합니다.
        naming:
          physical-strategy: com.lumeneditor.www.config.NamingStrategy # 커스텀 네이밍 전략 클래스
          implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy # 스프링 부트의 기본 암시적 네이밍 전략
      properties:
        hibernate:
          format_sql: true # SQL 포맷을 보기 좋게 출력합니다.
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect # MySQL InnoDB Dialect를 사용합니다.


# JWT 설정
jwt:
  secret: 64461f01e1s23mf93ngrg2fd9501ce59142452199ff112fb5404c8e7e98e3ff

redis:
   host: localhost # Redis 서버 호스트
   port: 6379 # Redis 서버 포트
   password: 123 # Redis 암호 (설정이 필요한 경우)
   lettuce:
     pool: # 커넥션 풀 설정 (필요한 경우)
       max-active: 8
       max-idle: 8
       min-idle: 0
